sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: "oss-cn-hangzhou.aliyuncs.com"
    bucket-name: "suiseiseki-javaai"
    access-key-secret: AEBDE44664F25AE1F6A97699E2BB742A
    access-key-id: LTAI5tDw6oMaT3CEEBZtzqk9
